### ISSUE TITLE
[feature/idea] customer groups

### ISSUE THREAD

**Issue by GeoffWilliams** [jeffmccune/ncio#11]
I had an idea earlier about using NCIO to upgrade between different versions of PE by dumping just customer's rules, omitting the build in ones.

This might let us do something like dump the customer-owned rules from say PE 2016.4.2 and then loading them into PE 2017.3.0 when its becomes available, without having to worry about importing 'old' built-in rules and breaking things.

Would this be a useful feature?  I this might work as long as customers have another way to get any change they need into the puppet-owned rules - say through puppet code or some other tool that just deals with upgrades and installations

**Comment by jeffmccune** [comment]
Good idea, but ncio is in maintenance mode.  It does the thing it was originally intended to pretty well and I'd like to preserve that as best as possible.  I'll fix bugs and apply security patches, but I don't intend to add new features and functionality.  Suggest forking it if you'd like to see this feature.
